### ISSUE TITLE
New data integration API

### ISSUE THREAD

**Issue by aecio** [VIDA-NYU/bdi-kit#52]
We'll use this issue to track the implementation of the new bdi-kit API.

Implementation:
- [x] `bdi.match_columns()`
- [x] `bdi.top_matches()`
- [x] `bdi.preview_domains()`
- [x] `bdi.preview_value_matches()`
- [x] `bdi.update_matches()`
- [x] `bdi.match_values()`
- [x] `bdi.materialize_mapping()`

Documentation:
- [ ] Make sure that all public functions have pydocs
- [ ] Make sure that readthedocs is generating API documentation
- [ ] Create a notebook demonstrating the API usage

**Comment by EduardoPena** [comment]
I suggest some naming refactoring before integrating this branch into the devel. For example:
Instead of ```bdikit.mapping_algorithms.column_mapping.algorithms``` we could have ```bdikit.matching.column.algorithms```; the same for value matching: ```bdikit.matching.value.algorithms```. For a naming standard, I would suggest that we stick to the schema matching/mapping conventions from a textbook book like: 
https://link.springer.com/book/10.1007/978-3-642-16518-4
